[package]
name = "jsonxf"
version = "0.5.0"
authors = ["pete gamache <pete@gamache.org>"]

[dependencies]
getopts = "0.2"

[lib]
name = "jsonxf"
path = "src/jsonxf.rs"

[[bin]]
name = "jsonxf"
path = "src/main.rs"
doc = false

